###

GET https://jsonplaceholder.typicode.com/users HTTP/1.1

###

GET https://fakerapi.it/api/v1/users?_quantity=100

###

GET https://fakerapi.it/api/v1/images?_quantity=1&_type=kittens&_height=300:w
